# Generated by Django 3.2.8 on 2022-02-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eachcategory',
            options={'ordering': ('Course',)},
        ),
        migrations.RenameField(
            model_name='eachcategory',
            old_name='Name',
            new_name='Course',
        ),
        migrations.AlterField(
            model_name='eachcategory',
            name='Description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eachcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='blog.allcategory'),
        ),
    ]
