# Generated by Django 3.2.8 on 2022-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_description_eachcategory_blogdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcategory',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='eachcategory',
            name='Title',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
